#:schema https://json.schemastore.org/any.json

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/myfiles"
delay = 50
entrypoint = ["./tmp/main"]
exclude_dir = ["tmp"]
include_dir = [
  "cmd",
  "controller",
  "model",
  "service",
  "validation",
  "views",
]
include_ext = ["go", "html", "css", "sql"]

[log]
main_only = true

[misc]
clean_on_exit = false

[proxy]
enabled = true
proxy_port = 3001
app_port = 3000
